param(
  [string]$KeyPath,
  [string]$Impersonate
)

# Helper to configure Google ADC for the credential manager.
# Usage examples:
#   .\setup_gcp_adc.ps1 -KeyPath "C:\path\to\key.json"
#   .\setup_gcp_adc.ps1 -Impersonate "infinity-x-one-systems@appspot.gserviceaccount.com"

$envFile = Join-Path -Path (Split-Path -Parent $PSScriptRoot) -ChildPath '.env'
if (-not (Test-Path $envFile)) {
  Write-Host "Creating .env file at $envFile"
  "# Generated by setup_gcp_adc.ps1" | Out-File -FilePath $envFile -Encoding utf8
}

if ($KeyPath) {
  if (-not (Test-Path $KeyPath)) {
    Write-Error "Key file not found: $KeyPath"
    exit 2
  }

  # Update or add GOOGLE_APPLICATION_CREDENTIALS in .env
  $content = Get-Content $envFile -Raw
  if ($content -match 'GOOGLE_APPLICATION_CREDENTIALS=') {
    $content = $content -replace 'GOOGLE_APPLICATION_CREDENTIALS=.*','GOOGLE_APPLICATION_CREDENTIALS=' + $KeyPath
  } else {
    $content += "`nGOOGLE_APPLICATION_CREDENTIALS=$KeyPath`n"
  }
  $content | Out-File -FilePath $envFile -Encoding utf8
  Write-Host "Set GOOGLE_APPLICATION_CREDENTIALS in .env to: $KeyPath"
  Write-Host "Run: node cli.js validate"
  exit 0
}

if ($Impersonate) {
  # Use gcloud to configure application default credentials with impersonation
  Write-Host "Attempting ADC login with impersonation: $Impersonate"
  Write-Host "This requires gcloud SDK installed and you to have permission to impersonate the service account."

  $cmd = "gcloud auth application-default login --impersonate-service-account=$Impersonate"
  Write-Host "Running: $cmd"
  iex $cmd

  if ($LASTEXITCODE -eq 0) {
    Write-Host "ADC configured via impersonation. Run: node cli.js validate"
    exit 0
  } else {
    Write-Error "gcloud command failed with exit code $LASTEXITCODE"
    exit $LASTEXITCODE
  }
}

Write-Host "Provide either -KeyPath or -Impersonate. Example:" 
Write-Host "  .\setup_gcp_adc.ps1 -KeyPath 'C:\path\to\key.json'"
Write-Host "  .\setup_gcp_adc.ps1 -Impersonate 'infinity-x-one-systems@appspot.gserviceaccount.com'"
exit 1
